In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

In [3]:
df = pd.read_csv("/home/itl7/Documents/MLSecOps_exp2/irrigation_prediction.csv")

df.head()

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,Clay,6.14,36.48,0.42,2.17,21.90,31.19,1167.70,4.01,1.97,Wheat,Vegetative,Rabi,Rainfed,Reservoir,4.73,Yes,1.98,South,Low
1,Silt,6.41,50.56,0.38,0.23,36.50,26.01,831.28,10.72,16.82,Maize,Flowering,Zaid,Canal,Groundwater,12.22,Yes,33.56,Central,Medium
2,Sandy,7.71,40.07,1.09,2.18,41.83,76.41,1844.45,7.75,19.03,Cotton,Harvest,Rabi,Drip,Reservoir,5.52,Yes,34.62,South,Low
3,Clay,5.96,12.75,1.56,0.40,37.22,43.32,306.26,8.90,11.44,Wheat,Sowing,Kharif,Canal,Reservoir,1.43,Yes,84.03,North,Medium
4,Clay,7.76,18.58,0.95,2.52,22.38,86.44,1875.63,10.39,11.26,Cotton,Sowing,Zaid,Canal,River,2.52,No,60.86,South,Medium

In [4]:
print(df.shape)

print(df.info())

print(df.describe())

(10000, 20)
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Soil_Type                10000 non-null  str
 1   Soil_pH                  10000 non-null  float64
 2   Soil_Moisture            10000 non-null  float64
 3   Organic_Carbon           10000 non-null  float64
 4   Electrical_Conductivity  10000 non-null  float64
 5   Temperature_C            10000 non-null  float64
 6   Humidity                 10000 non-null  float64
 7   Rainfall_mm              10000 non-null  float64
 8   Sunlight_Hours           10000 non-null  float64
 9   Wind_Speed_kmh           10000 non-null  float64
 10  Crop_Type                10000 non-null  str
 11  Crop_Growth_Stage        10000 non-null  str
 12  Season                   10000 non-null  str
 13  Irrigation_Type          10000 non-null  str
 14  Water_Source             10000 non-null  str
 15  Field_Area_hectare       10000 non-null  float64
 16  Mulching_Used            10000 non-null  str
 17  Previous_Irrigation_mm   10000 non-null  float64
 18  Region                   10000 non-null  str
 19  Irrigation_Need          10000 non-null  str
dtypes: float64(11), str(9)
memory usage: 1.5 MB
None
            Soil_pH  Soil_Moisture  Organic_Carbon  Electrical_Conductivity  \
count  10000.000000   10000.000000    10000.000000             10000.000000
mean       6.487857      36.969207        0.944731                 1.791963
std        0.979963      16.430845        0.372406                 0.984202
min        4.800000       8.000000        0.300000                 0.100000
25%        5.640000      22.860000        0.620000                 0.940000
50%        6.470000      37.240000        0.950000                 1.780000
75%        7.350000      50.940000        1.260000                 2.650000
max        8.200000      65.000000        1.600000                 3.500000

       Temperature_C      Humidity   Rainfall_mm  Sunlight_Hours  \
count   10000.000000  10000.000000  10000.000000    10000.000000
mean       26.991423     60.080339   1252.499420        7.518538
std         8.664074     20.187973    715.582201        2.016077
min        12.000000     25.000000      0.380000        4.000000
25%        19.460000     42.855000    634.155000        5.760000
50%        27.090000     60.040000   1250.335000        7.560000
75%        34.500000     77.705000   1880.265000        9.260000
max        42.000000     95.000000   2499.690000       11.000000

       Wind_Speed_kmh  Field_Area_hectare  Previous_Irrigation_mm
count    10000.000000        10000.000000            10000.000000
mean        10.163545            7.598024               59.864122
std          5.670923            4.233919               34.483722
min          0.500000            0.300000                0.020000
25%          5.160000            3.950000               30.160000
50%         10.190000            7.540000               59.630000
75%         15.100000           11.202500               90.030000
max         20.000000           15.000000              119.990000

In [5]:
categorical = df.select_dtypes(include=["object"]).columns

encoders = {}

for col in categorical:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

df.head()

/tmp/ipykernel_12233/197411543.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical = df.select_dtypes(include=["object"]).columns

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,0,6.14,36.48,0.42,2.17,21.90,31.19,1167.70,4.01,1.97,5,3,1,2,2,4.73,1,1.98,3,1
1,3,6.41,50.56,0.38,0.23,36.50,26.01,831.28,10.72,16.82,1,0,2,0,0,12.22,1,33.56,0,2
2,2,7.71,40.07,1.09,2.18,41.83,76.41,1844.45,7.75,19.03,0,1,1,1,2,5.52,1,34.62,3,1
3,0,5.96,12.75,1.56,0.40,37.22,43.32,306.26,8.90,11.44,5,2,0,0,2,1.43,1,84.03,2,2
4,0,7.76,18.58,0.95,2.52,22.38,86.44,1875.63,10.39,11.26,0,2,2,0,3,2.52,0,60.86,3,2